import React, { Component } from "react";

class ImageSlider extends Component {
  state = {};
  render() {
    return (
      <div>
        <p>These are the frames' images generated by getVideoImage():</p>
      </div>
    );
  }
}

export default ImageSlider;
